/**
 * Machine-readable error codes returned to clients. The frontend switches on
 * `error.code`, never on `error.message` — messages can be reworded for
 * localization/tone without breaking client logic that depends on them.
 *
 * Convention: DOMAIN_CONDITION, uppercase snake case, one enum per bounded
 * context so codes never collide across modules.
 */
export enum ErrorCode {
  // Generic
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT = 'IDEMPOTENCY_KEY_CONFLICT',

  // Identity
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  OTP_INVALID_OR_EXPIRED = 'OTP_INVALID_OR_EXPIRED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  PROVIDER_NOT_VERIFIED = 'PROVIDER_NOT_VERIFIED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',

  // Catalog
  LISTING_NOT_LIVE = 'LISTING_NOT_LIVE',
  LISTING_PHOTO_REQUIRED = 'LISTING_PHOTO_REQUIRED',
  LISTING_PHOTO_LIMIT_EXCEEDED = 'LISTING_PHOTO_LIMIT_EXCEEDED',
  CATEGORY_ATTRIBUTE_INVALID = 'CATEGORY_ATTRIBUTE_INVALID',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_INACTIVE = 'CATEGORY_INACTIVE',

  // Booking
  BOOKING_DATES_UNAVAILABLE = 'BOOKING_DATES_UNAVAILABLE',
  BOOKING_INVALID_STATE_TRANSITION = 'BOOKING_INVALID_STATE_TRANSITION',
  BOOKING_NOT_APPROVABLE = 'BOOKING_NOT_APPROVABLE',
  BOOKING_DATE_RANGE_INVALID = 'BOOKING_DATE_RANGE_INVALID',
  BOOKING_NOT_ACTIVE = 'BOOKING_NOT_ACTIVE',
  EXTENSION_REQUEST_INVALID_STATE = 'EXTENSION_REQUEST_INVALID_STATE',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // Trust & disputes
  REVIEW_BOOKING_NOT_COMPLETED = 'REVIEW_BOOKING_NOT_COMPLETED',
  REVIEW_ALREADY_SUBMITTED = 'REVIEW_ALREADY_SUBMITTED',
  DISPUTE_INVALID_STATE = 'DISPUTE_INVALID_STATE',
  DISPUTE_DEDUCTION_EXCEEDS_DEPOSIT = 'DISPUTE_DEDUCTION_EXCEEDS_DEPOSIT',

  // Identity — verification documents
  VERIFICATION_DOCUMENT_ALREADY_REVIEWED = 'VERIFICATION_DOCUMENT_ALREADY_REVIEWED',
}
