export enum NotificationType {
  BOOKING_CREATED = 'booking_created',
  BOOKING_APPROVED = 'booking_approved',
  BOOKING_DECLINED = 'booking_declined',
  BOOKING_CANCELLED = 'booking_cancelled',
  BOOKING_HANDED_OVER = 'booking_handed_over',
  BOOKING_RETURNED = 'booking_returned',
  BOOKING_DEPOSIT_RELEASED = 'booking_deposit_released',
  BOOKING_DISPUTED = 'booking_disputed',
  BOOKING_EXTENSION_REQUESTED = 'booking_extension_requested',
  BOOKING_EXTENSION_RESOLVED = 'booking_extension_resolved',
  PROVIDER_VERIFIED = 'provider_verified',
  PROVIDER_REJECTED = 'provider_rejected',
  LISTING_APPROVED = 'listing_approved',
  LISTING_REJECTED = 'listing_rejected',
  VERIFICATION_DOCUMENT_REVIEWED = 'verification_document_reviewed',
  MESSAGE_RECEIVED = 'message_received',
}
